modLoader="javafml"
loaderVersion="[47,)"
license="Apache License version 2.0"

[[mods]]
modId="the_hobbit_mod"
version="1.3.0"
displayName="The Hobbit Mod"
displayURL="https://mcreator.net/modification/92049/hobbit-mod"
logoFile="logo.png"
credits="gh5674"
authors="gh5674"
description="Introduces The Hobbit into Minecraft."

[[dependencies.the_hobbit_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




